import { Author } from "../modules/authors/author.model.js";

const AUTHOR_NAMES = [
  "Jane Austen",
  "George Orwell",
  "Virginia Woolf",
  "Ernest Hemingway",
  "Toni Morrison",
  "Gabriel García Márquez",
  "Haruki Murakami",
  "Margaret Atwood",
  "Kazuo Ishiguro",
  "Zadie Smith",
  "Chimamanda Ngozi Adichie",
  "Salman Rushdie",
  "Donna Tartt",
  "Colson Whitehead",
  "Ocean Vuong",
  "Jhumpa Lahiri",
  "Hanya Yanagihara",
  "Celeste Ng",
  "Anthony Doerr",
  "Emily St. John Mandel",
  "Ann Patchett",
  "Richard Powers",
  "Louise Erdrich",
  "Michael Chabon",
  "Jonathan Franzen",
  "Don DeLillo",
  "Thomas Pynchon",
  "Cormac McCarthy",
  "Alice Munro",
  "Ian McEwan",
  "Julian Barnes",
  "Hilary Mantel",
  "Maggie O'Farrell",
  "Tana French",
  "Tayari Jones",
  "Brit Bennett",
  "Yaa Gyasi",
  "Sally Rooney",
  "Emma Donoghue",
  "Rachel Cusk",
  "Ali Smith",
  "Helen Oyeyemi",
  "Patrick Ness",
  "Neil Gaiman",
  "Ursula K. Le Guin",
  "Octavia Butler",
  "N.K. Jemisin",
  "Becky Chambers",
  "Ted Chiang",
  "John le Carré",
  "Gillian Flynn",
  "Denise Mina",
  "Walter Mosley",
  "James Baldwin",
  "Ralph Ellison",
  "Zora Neale Hurston",
  "Langston Hughes",
  "Maya Angelou",
  "Alice Walker",
  "Ta-Nehisi Coates",
  "Fyodor Dostoevsky",
  "Leo Tolstoy",
  "Franz Kafka",
  "James Joyce",
  "Marcel Proust",
  "Albert Camus",
  "Jorge Luis Borges",
  "Italo Calvino",
  "Sylvia Plath",
  "Joan Didion",
  "Kurt Vonnegut",
  "Ray Bradbury",
  "Philip K. Dick",
  "Stephen King",
  "Shirley Jackson",
  "Isabel Allende",
  "Elena Ferrante",
  "Olga Tokarczuk",
  "Min Jin Lee",
  "Han Kang",
  "Arundhati Roy",
  "Vikram Seth",
  "George R.R. Martin",
  "J.R.R. Tolkien",
  "C.S. Lewis",
  "Agatha Christie",
  "Raymond Chandler",
  "Dashiell Hammett",
  "Patricia Highsmith",
  "Truman Capote",
  "Douglas Adams",
  "Terry Pratchett",
  "William Gibson",
  "Margaret Laurence",
  "Mordecai Richler",
  "Willa Cather",
  "Edith Wharton",
  "F. Scott Fitzgerald",
  "John Steinbeck",
  "Harper Lee",
  "T.S. Eliot",
  "W.B. Yeats",
  "Robert Frost",
  "Mary Oliver",
  "Wole Soyinka",
  "Ngũgĩ wa Thiong'o",
  "Douglas Stuart",
  "Marlon James",
  "Bernardine Evaristo",
  "Eimear McBride",
  "Kevin Barry",
  "Miriam Toews",
  "Dave Eggers",
  "George Saunders",
  "Lydia Davis",
  "Elizabeth Strout",
  "Barbara Kingsolver",
  "Junot Díaz",
  "Susanna Clarke",
  "V.S. Naipaul",
];

export const seedAuthors = async () => {
  for (const name of AUTHOR_NAMES) {
    const [author] = await Author.findOrCreate({
      where: { name },
      defaults: { name },
    });
    if (author.isNewRecord) {
      console.log(`Author "${name}" created.`);
    }
  }
  console.log(`Seeded ${AUTHOR_NAMES.length} authors.`);
};
